spring.config.import=optional:classpath:application-segreto.properties
#==================================
# = Datasource
#==================================
spring.application.name=Progetto_SIW
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql=trace
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/partite
spring.datasource.username=postgres
spring.datasource.password=Giginski12#@
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#==================================
# = Web server
#==================================
server.port=${PORT:8080}
#==================================
# = Thymeleaf configurations
#==================================
spring.thymeleaf.check-template-location=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.servlet.content-type=text/html
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.encoding=UTF-8
#==================================
# = Configurazione OAuth (GitHub)
#==================================
spring.security.oauth2.client.registration.github.client-id=Ov23liHyTLa6JXgQvujT
spring.security.oauth2.client.registration.github.client-secret=7ed3f0af9c66d5b548ea00d598630a2dec0ee5ed