spring.config.import=optional:classpath:application-segreto.properties
#==================================
# = Datasource
#==================================
spring.application.name=Progetto_SIW
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql=trace
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-d9d6ninaqgkc73d0393g-a:5432/partite
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#==================================
# = Web server
#==================================
server.port=${PORT:8080}
#==================================
# = Thymeleaf configurations
#==================================
spring.thymeleaf.check-template-location=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.servlet.content-type=text/html
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.encoding=UTF-8
#==================================
# = Configurazione OAuth (GitHub)
#==================================
spring.security.oauth2.client.registration.github.client-id=${OAUTH_CLIENT_ID:}
spring.security.oauth2.client.registration.github.client-secret=${OAUTH_CLIENT_SECRET:}